# 여기서 쓸만한건 where과 argmax정도
- where은 참 거짓을 판별해주고, argmax는 최댓값의 인덱스를 반환해줌

In [1]:
import numpy as np

In [21]:
a = [[1, 2, 3, 4, 5]
     , [9, 8, 7, 6, 5]]
b = np.array(a)

In [22]:
b.shape

(2, 5)

In [23]:
b = np.array(a)
b[1, 0]

9

In [25]:
b = np.array(a)
b[0 : 2, 1 : 3]

array([[2, 3],
       [8, 7]])

In [27]:
b = np.array(a)
b[b >= 5]

array([5, 9, 8, 7, 6, 5])

In [29]:
b = np.array(a)
b[(b >= 5) & (b < 9)]

array([5, 8, 7, 6, 5])

In [30]:
np.sum(b)

50

In [32]:
np.argmax(b, axis = 0) # 최댓값의 인덱스 위치, axis도 사용가능

array([1, 1, 1, 1, 0], dtype=int64)

In [33]:
np.where(b > 3, 1, 0) # 조건, 참, 거짓

array([[0, 0, 0, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.where(b > 3, 1, b) # 참이면 1 거짓이면 그대로

array([[1, 2, 3, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
c = np.linspace(1, 10, 10)
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])